spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/app_trade_db
    username: user
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8080
