spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: ${datasource_url:jdbc:mariadb://localhost:3306/app_trade_db}
    username: ${datasource_username:user}
    password: ${datasource_password:12345678}
  banner:
    location: classpath:custom-banner.txt

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: ${server_port:8080}

api:
  base-url:
    v1: /api/v1